<?php

namespace Log210\LivraisonBundle\EntityRepository;

use Log210\CommonBundle\EntityRepository\EntityRepository;
use Log210\LivraisonBundle\Entity\Menu;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository
{
    public function makeEntity()
    {
        return new Menu();
    }
}
